version: '3.8'

services:
  app:
    image: php:8.2-apache
    ports:
      - "8081:80"
    volumes:
      - portfolio:/var/www/html
    working_dir: /var/www/html

volumes:
  portfolio:
    external: true
